[package]
name = "taskeo"
version = "0.2.0"
edition = "2018"

[[bin]]
name = "keo"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ansi_term = "0.12"
regex = "1.5"
anyhow = "1.0"
bincode = "1.3"
